version: '2'

services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./.data:/var/lib/mysql:cached
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/my.conf
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "trp"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "root"
      MYSQL_HOST: ""
      TZ: "Asia/Tokyo"
    ports:
      - "3308:3306"
    restart: always